package com.yhh.spbootssm.domain;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test.id
     *
     * @mbggenerated Sun Nov 26 10:00:41 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test.name
     *
     * @mbggenerated Sun Nov 26 10:00:41 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test.age
     *
     * @mbggenerated Sun Nov 26 10:00:41 CST 2017
     */
    private Integer age;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test.id
     *
     * @return the value of t_test.id
     *
     * @mbggenerated Sun Nov 26 10:00:41 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test.id
     *
     * @param id the value for t_test.id
     *
     * @mbggenerated Sun Nov 26 10:00:41 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test.name
     *
     * @return the value of t_test.name
     *
     * @mbggenerated Sun Nov 26 10:00:41 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test.name
     *
     * @param name the value for t_test.name
     *
     * @mbggenerated Sun Nov 26 10:00:41 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test.age
     *
     * @return the value of t_test.age
     *
     * @mbggenerated Sun Nov 26 10:00:41 CST 2017
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test.age
     *
     * @param age the value for t_test.age
     *
     * @mbggenerated Sun Nov 26 10:00:41 CST 2017
     */
    public void setAge(Integer age) {
        this.age = age;
    }
}